const factionDescription = {
  Pirates: 'Pirates are great at movement. “Shanghai” lets you move an opponent’s minion to elsewhere, while “Full Sail” lets you move your entire crew. Unless destroyed, First Mates never enter the discard pile, moving after after each time they score a base. Pirates are a great counter pick against any faction that relies on its low power minions—that’s putting it lightly, power 2 minions are decimated by this faction.',
  Dinosaurs: ' The original powerhouse faction. The Dinosaurs allow you to overpower your opponent with minions that are stronger than most. King Rex can swing a base in your favor with its massive 7 power. The Dinosaurs come with a variety of cards that protect your minions from destruction as well as quick removal of some of your opponents minions. Although they are slow they work best with a faction that allows multiple minion and/or action plays for maximum damage. \n',
  Ninjas: 'Ninjas have the ability to win points on any base. The Ninjas special abilities allow you activate effects before a base is scoring, which can offer a chance to swing the base your way and steal some easy points. Ninjas have decent destruction cards and have the ability to swap your current minions in play with minions in your hand, allowing you to replay your most powerful cards.',
  Zombies: 'The ultimate in recursion, zombies utilize the discard pile to the fullest. Every turn, you have the option to play minions from the discard pile and/or return cards from the discard pile to your hand. With this faction there are no bad pairings, as each lends a new opportunity to repeat the most desired effects. Zombies lack movement, and many of their minions have low power, but they are still one of the strongest factions in the game.',
  Robots: 'Robots are the first Smash Up ’swarm’ faction. They have 18 minions and only two actions which means that you will always have minions on bases. They specialize in extra minion plays and powerful power creep with their collection of Microbots. Some of their downsides are not having any movement or the lack of actions. This puts a lot of pressure on the partner faction.',
  Tricksters: 'The Tricksters specialize in preventing and annoying your opponent from making the ideal play. The Leprechaun destroys any of your opponents minions that are played with less power. With multiple cards that make your opponents discard, there are always ways to sabotage your opponents. The Tricksters require a bit of planning to truly succeed but when played correctly the Tricksters can be devastating.',
  Wizards: 'If you need extra action plays look no further than the wizards. All of their minions and actions help you to play more actions. They are also a good pick if you’re looking to cycle through your deck quickly. Though versatile, they lack power, so pick them for support. Not recommended for beginners.',
  Aliens: 'With aliens, it’s a sneaky road to victory. You can annoy your opponents by returning their cards to their hands, but this can work to your detriment. Your goal should be to beam up and replay your invaders over and over to farm VPs. Aliens also have some control over bases, with cards like “Jammed Signal”, which cancels the ability of a base, and “Terraforming”, which allows you to switch out a base that you don’t like for a new one. Pair the aliens with another faction that returns cards to the hand if you want your friends to hate you.',
  Killer_Plants: 'Going Green? Stay away from these guys. The Killer Plants are a slow faction that can do a little bit of everything. Great card draw with Water Lilly, extra plays with cards like Blossom and Sprout can catch your opponents off guard. Powerful cards like Overgrow can swing a base in your favor really quickly. The faction contains 3 minions of power 5. Pair them with Zombies if you want a laugh.',
  Steampunks: 'The Steampunks are the first of many, many “play-on-base actions” factions. The Steampunks are the most well-rounded of these, as they do just a bit of everything. “Aggromotive” and “Rotary Slug Thrower” add a ton of power to a base. “Captain Ahab” and “Zeppelin” are great options for movement. Run out of play-on-base actions? Mechanic and Scrap Diving return them to you quick. You can’t go wrong with Steampunks. They’re a solid pick, which is why they’re at the foundation of OG Smash Up. ',
  Ghosts: 'If your looking for a fun challenge, see if you can win with 0 cards in your hand. This is the name of the game for Ghosts. Many cards benefit from having 2 or fewer cards in your hand, like “Haunting”, a minion that gains +3 power, and “Shady Deal”, which nets you a VP. This may seem counterintuitive, but pair the Ghosts with a faction that excels in draw-power. You’ll want to draw some cards so that you can unload them later on. Boo! Scared ya...',
  Bear_Cavalry: 'Best way to arrive to battle? Riding on a bear of course! Bear Cavalry move your opponents minions to other bases, where they will be destroyed in an instant. Straight to the gulag! Bear Cavalry have one of the most powerful boss minions in the game: General Ivan. He’s power-6, and prevents destruction of all your minions. With a plethora of movement cards, you can spread out and get some unpredictable plays. The downside of this faction is the lack of recursion and extra plays. \n',
  Elder_Things: 'Elderrrrr',
  Miskatonik_University: 'uniiii',
  Minions_of_Cthulhu: 'Minionssssss',
  Innsmouth: 'FIsh dudes',
  Super_Spies: 'Secret Spies',
  Time_Travelers: 'Time dude',
  Cyborg_Apes: 'Apessss',
  Shapeshifters: 'slimyyyyyy',
  Vampires: 'Bloodsuckaaa',
  Giant_Ants: 'Big ants',
  Werewolves: 'Wolvessss',
  Mad_Scientists: 'Maddddddd',
  Princesses: 'Queeenzzz',
  Kitty_Cats: 'Kittens',
  Fairies: 'Fairiessss',
  Mythic_Horses: 'My little ponies',
  Dwarves: 'Gem lovers',
  Halflings: 'Hobbits',
  Elves: 'Legolasss',
  Mages: 'Better Wizards',
  Orcs: 'SAURONS army',
  Warriors: 'Noble knights',
  Clerics: 'Heal me',
  Thives: 'Gimme da loot',
  Sharks: 'Not food',
  Superheroes: 'Superman',
  Tornados: 'Kansas',
  Mythic_Greeks: 'Greek Gods',
  Dragons: 'Donkeys Wifey',
  Astroknights: 'Star...',
  Changerbots: 'Trans..',
  Ignobles: 'Game of who',
  Star_Roamers: 'Star tttttt',
  Grannies: 'Old ladies',
  Explorers: 'Columbus',
  Rock_Stars: 'Rockinggggg',
  Teddy_Bears: 'Cuddly fellas',
  Magical_Girls: 'Anime',
  Itty_Critters: 'Pokem...',
  Kaiju: 'GODZILLA',
  Mega_Troopers: 'Power Ra...',
  Sheep: 'Baaaaa',
  Disco_Dancers: 'Groovy',
  Vigilantes: 'Good Guys',
  Truckers: 'We striking',
  Kung_Fu_Fighters: 'Kicking ass, taking names',
  Smash_Up_All_Stars: 'The best',
  Geeks: 'Nerds',
  Ancient_Egyptians: 'yugioh',
  Samurai: 'Tom Cruise?',
  Vikings: 'IKEA',
  Cowboys: 'Texas boyz',
  Luchadors: 'Viva la mehico',
  Musketeers: 'Swords not muskets',
  Mounties: 'Aboot That',
  Sumo_Wrestlers: 'Thicc boizz',
  Penguins: 'Kowalski',
  Russian_Fairy_Tales: 'Transform ya butt',
  Anansi_Tales: 'Village Stories',
  Ancient_Incas: 'Native Dudes',
  Grimms_Fairy_Tales: 'Folklore',
  Polynesian_Voyagers: 'Gimme da island',
};

export default factionDescription;
