const factionDescription = {
  Pirates: 'Pirate D',
  Dinosaurs: 'Dino D',
  Ninjas: 'ninja d',
  Zombies: 'zombies',
  Robots: 'robot d',
  Tricksters: 'tricksters',
  Wizards: 'Wizzy',
  Aliens: 'aliennnnzzzz',
  Killer_Plants: 'Plantzzz',
  Steampunks: 'Steampunks',
  Ghosts: 'spookyyyyy',
  Bear_Cavalry: 'Russians',
  Elder_Things: 'Elderrrrr',
  Miskatonik_University: 'uniiii',
  Minions_of_Cthulhu: 'Minionssssss',
  Innsmouth: 'FIsh dudes',
  Super_Spies: 'Secret Spies',
  Time_Travelers: 'Time dude',
  Cyborg_Apes: 'Apessss',
  Shapeshifters: 'slimyyyyyy',
  Vampires: 'Bloodsuckaaa',
  Giant_Ants: 'Big ants',
  Werewolves: 'Wolvessss',
  Mad_Scientists: 'Maddddddd',
  Princesses: 'Queeenzzz',
  Kitty_Cats: 'Kittens',
  Fairies: 'Fairiessss',
  Mythic_Horses: 'My little ponies',
  Dwarves: 'Gem lovers',
  Halflings: 'Hobbits',
  Elves: 'Legolasss',
  Mages: 'Better Wizards',
  Orcs: 'SAURONS army',
  Warriors: 'Noble knights',
  Thives: 'Gimme da loot',
  Sharks: 'Not food',
  Superheroes: 'Superman',
  Tornados: 'Kansas',
  Mythic_Greeks: 'Greek Gods',
  Dragons: 'Donkeys Wifey',
  Astroknights: 'Star...',
  Changerbots: 'Trans..',
  Ignobles: 'Game of who',
  Star_Roamers: 'Star tttttt',
  Grannies: 'Old ladies',
  Explorers: 'Columbus',
  Rock_Stars: 'Rockinggggg',
  Teddy_Bears: 'Cuddly fellas',
  Magical_Girls: 'Anime',
  Itty_Critters: 'Pokem...',
  Kaiju: 'GODZILLA',
  Mega_Troopers: 'Power Ra...',
  Sheep: 'Baaaaa',
  Disco_Dancers: 'Groovy',
  Vigilantes: 'Good Guys',
  Truckers: 'We striking',
  Kung_Fu_Fighters: 'Kicking ass, taking names',
  Smash_Up_All_Stars: 'The best',
  Geeks: 'Nerds',
  Ancient_Egyptians: 'yugioh',
  Samurai: 'Tom Cruise?',
  Vikings: 'IKEA',
  Cowboys: 'Texas boyz',
  Luchadors: 'Viva la mehico',
  Musketeers: 'Swords not muskets',
  Mounties: 'Aboot That',
  Sumo_Wrestlers: 'Thicc boizz',
  Penguins: 'Kowalski',
  Russian_Fairy_Tales: 'Transform ya butt',
  Anansi_Tales: 'Village Stories',
  Ancient_Incas: 'Native Dudes',
  Grimms_Fairy_Tales: 'Folklore',
  Polynesian_Voyagers: 'Gimme da island',
};

export default factionDescription;
